name: 'dremix1'

services:
  remix:
    #    image: app-dremix1-node:latest
    build:
      context: ./docker/node
      args:
        - UID=1000
        - GID=1000
        - USER_NAME=dev
    user: 1000:1000
    volumes:
      - ./source:/app
    ports:
      - 3000:3000
    networks:
      - postgres
    command:
      - npm
      - run
      - dev
    depends_on:
      - db

  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=dremix1
      - PGDATA=/var/lib/postgresql/data
    ports:
      - '5432:5432'
    expose:
      - '5432'
    networks:
      - postgres
    volumes: 
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local
networks:
  postgres: 
    driver: bridge